### ISSUE TITLE
Extension only opens the first item

### ISSUE THREAD

**Issue by cesarfd** [omon/feedly_open_background_tab#1]
Something has changed on Feedly, this is what happens now:

- Go to the "All" section.
- Begin navigating the items.
- Open any item (1st, 2nd, 3rd, etc...) in the background. All the opened tabs have the first item of the list.

Curiously enough, if you do the same thing on the recently read section it works fine.

Edit: better explanation.

**Comment by omon** [comment]
thank you for your feedback.
I tried it in my environment, but it didn't reproduce.
I would love to reproduce it and try the fix.

If you like, can you tell me the environment and the shortcut keys you have set?
best regard.

**Comment by cesarfd** [comment]
Tried on:

- Firefox 85 beta 8, macOS 11.1.
- addon version 1.0.
- The selected key for background tab is `h`.

Steps to reproduce:

- Enter Feedly with a few items to see.
- Select the "All" or the "recently read" sections. Feedly will show the articles as usual. 
- The only article that will be opened on the background is the first one.

Note: I've realized it only happens in Article View mode. The rest (title only, magazine, cards) seem to work fine.

Thank you for your quick response!

**Comment by omon** [comment]
thanks for your info.

When I tried it, it certainly happened in the article view.

I changed the process a little in ver2.0 and confirmed that the article view, title only view, magazine view, and card view all work.
Now mozila is reviewing the registration of Ver2.0, so I hope that it will be available once the review is completed.
Thank you.

**Comment by cesarfd** [comment]
Thank you, the update works perfect!
